services:
    postgres:
        image: postgres:17
        environment:
            POSTGRES_USER: "${DB_USER:-petrohaus}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-petrohaus}"
            POSTGRES_DB: "${DB_NAME:-petrohaus}"
        ports:
            - 127.0.0.1:5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
