services:
    postgres:
        image: postgis/postgis:17-3.5-alpine
        platform: linux/amd64
        environment:
            POSTGRES_USER: "${DB_USER:-petrohaus}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-petrohaus}"
            POSTGRES_DB: "${DB_NAME:-petrohaus}"
        ports:
            - 127.0.0.1:5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - petrohaus

    buggregator:
        image: ghcr.io/buggregator/server:latest
        pull_policy: always
        ports:
            - 127.0.0.1:8000:8000
            - 127.0.0.1:1025:1025
            - 127.0.0.1:9912:9912
            - 127.0.0.1:9913:9913
        networks:
            - petrohaus

networks:
    petrohaus:
        driver: bridge
volumes:
    postgres_data:
