app = 'petrohaus'
primary_region = 'eze'
console_command = 'php /var/www/html/artisan tinker'

[build]
  image = "ghcr.io/mayocca/petrohaus:main"

[env]
  APP_URL = 'https://petrohaus.fly.dev'
  OCTANE_HTTPS = 'true'
  SENTRY_ENABLE_LOGS = 'true'
  SENTRY_TRACES_SAMPLE_RATE = '0.1'
  SENTRY_PROFILES_SAMPLE_RATE = '0.1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = 256
  cpus = 1
  cpu_kind = 'shared'
