app = 'petrohaus'
primary_region = 'eze'
console_command = 'php /var/www/html/artisan tinker'

[build]
  dockerfile = 'Dockerfile'
  # image = "ghcr.io/mayocca/petrohaus:main"

[env]
  APP_ENV = 'production'
  APP_URL = 'https://petrohaus.fly.dev'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
