app = 'petrohaus'
primary_region = 'eze'
console_command = 'php /var/www/html/artisan tinker'

[build]
  image = "ghcr.io/mayocca/petrohaus:main"

[env]
  APP_URL = 'https://petrohaus.fly.dev'

[http_service]
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
