name: Linting and Style Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: [pint, phpstan]
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Install Dependencies
        run: |
          nix develop --command composer install --prefer-dist --no-progress --no-suggest
          npm install

      - name: Run Pint
        if: matrix.tool == 'pint'
        continue-on-error: true
        run: nix develop --command vendor/bin/pint --test

      - name: Run PHPStan
        if: matrix.tool == 'phpstan'
        continue-on-error: true
        run: nix develop --command vendor/bin/phpstan analyse --memory-limit=-1
