name: Linting and Style Checks

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    environment: Testing
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Install Dependencies
        run: |
          nix develop --command composer install --prefer-dist --no-progress --no-suggest
          npm install

      - name: Run Pint
        run: nix develop --command vendor/bin/pint --test
